<?php
/**
 * @var Laminas\View\Renderer\PhpRenderer $this
 */
?>
<footer class="main-footer">
    <div class="main-footer__bottom">
        <div class="container main-footer__bottom-container">
            <div class="main-footer__copyright">
                <div>
                    <span>&copy; Gobierno de Canarias</span>
                </div>
                <div>
                    <span>
                        <a href="https://www.gobiernodecanarias.org/principal/avisolegal.html">
                            Aviso legal
                        </a>
                    </span>
                    <span>
                        <a href="https://www.gobiernodecanarias.org/eucd/politica_privacidad/">
                            Pol&iacute;tica de privacidad
                        </a>
                    </span>
                </div>
            </div>
        </div>
    </div>
</footer>
